### ISSUE TITLE
Move Tilesheets repository to HydraWiki GitHub organization

### ISSUE THREAD

**Issue by Alexia** [HydraWiki/Tilesheets#14]
Are there any objections to transferring this repository to the @HydraWiki organization?  We are working consolidating all of the various wiki repositories under a new organization structure that will allow us to more easily interact with public contributors.

https://github.com/HydraWiki

**Comment by elifoster** [comment]
As long as @retep998 and I have push access to it, and OreDict still, I don't really have any objections.

**Comment by Alexia** [comment]
You're fast!  I just sent the invites out and the repositories will not be moved until both of you have responded to them.

**Comment by retep998** [comment]
There's already another Tilesheets repo but for a different extension. What names will be chosen to differentiate them?

**Comment by elifoster** [comment]
No there isn't? There's a SpriteSheet extension, which was on CurseStaff originally IIRC.

**Comment by retep998** [comment]
Oh, tilesheet vs spritesheet. Don't mind me, I apparently can't read.

**Comment by Alexia** [comment]
I see both of you have your access setup.  I will start moving the repositories over soon.
