### ISSUE TITLE
API needed

### ISSUE THREAD

**Issue by elifoster** [HydraWiki/Tilesheets#2]
The extension needs an API. Here's what is needed:

* [x] List sheets
* [x] Add sheets
* [x] Delete sheets
* [x] Edit sheets
* [x] List tiles with filtering by mod
* [x] Add tiles
* [x] Delete tiles
* [x] Edit tiles

Do all work on the API branch until fully working.

**Comment by cblair91** [comment]
Tilesheet extension
1. Get list of tilesheets (returns id, name, sizes)
2. Add tilesheet (specify name, sizes)
3. Remove tilesheet (specify id)
4. Edit tilesheet (specify id, sizes)
4. Get list of tiles (filter by mod abbreviation) (returns id, name, mod, x, y)
5. Add tiles (specify mod, name, x, y)
6. Remove tiles (specify id)
7. Edit tiles (specify id and at least one of name, x, y)
