### ISSUE TITLE
[API] Tiles query broken

### ISSUE THREAD

**Issue by xbony2** [HydraWiki/Tilesheets#21]
I was trying to make a tile deletion script because I was too lazy to delete the tiles manually, but it didn't work.
```ruby
# Copyright (C) 2016, Eric Schneider (xbony2)
# All rights reserved.

require "mediawiki/butt"

butt = MediaWiki::Butt.new("http://ftb.gamepedia.com")

puts "Please enter the password."
butt.login("ESAEBSAD", gets.chomp)

puts "Please enter the tilesheet abbreviation."
tilesheet = gets.chomp

tiles = butt.post({action: "query", list: "tiles", tslimit: 500, tsmod: tilesheet})

#butt.post({action: "deletetiles", tsids: tiles["query"]["tiles"].keys, tssummary: "", tstoken: butt.get_token("edit")})
puts tiles.to_s
```
returns
```ruby
{"batchcomplete"=>"", "query"=>{"tiles"=>[]}}
```
Showing that the query seems to be broken or that I'm missing something.

(Also TODO: delete tilesheet "ESAEBSADTEST" on the FTB Wiki once possible)

**Comment by elifoster** [comment]
This works fine for me http://ftb.gamepedia.com/api.php?action=query&list=tiles&tsmod=V&tslimit=45

**Comment by xbony2** [comment]
It's sort working and sort of not working. I'm in a shit mood and don't really want to explain >.> plus I need to test it a little bit more before being sure of anything.

**Comment by Alexia** [comment]
Ha.  The MediaWiki Butt request is what led me to #20.  It showed up in the New Relic error logs.

**Comment by xbony2** [comment]
Tilesheet ESAEBSADTEST was deleted (me thinks?) so that's probably why this isn't working.

My mood is okay now too, but the explanation for that is a little bit weird >.>
