### ISSUE TITLE
Description length is too short

### ISSUE THREAD

**Issue by retep998** [HydraWiki/Tilesheets#29]
https://github.com/HydraWiki/Tilesheets/blob/master/install/sql/ext_tilesheet_languages.sql#L5
```sql
 `description` varchar(100)
```
This is way too short for some descriptions, in particular GT6 where `&bConverts 1 HU into +1 K per 100kg/&4Melts down when stored Heat is too much! (2500 K)/Can put Blocks around it on Fire! (4m)/&8Tool to harvest: &fPickaxe (0)/&7Contains 7.0 Units of Clay/Melt: 2000 K - Boil: 4000 K - Weight: 1392.355 kg` was truncated to `&bConverts 1 HU into +1 K per 100kg/&4Melts down when stored Heat is too much! (2500 K)/Can put Bloc`

**Comment by elifoster** [comment]
What should be the size?

**Comment by retep998** [comment]
Maybe instead of using `VARCHAR` you could just use `TEXT` instead which has a limit of 65 thousand.

**Comment by elifoster** [comment]
Ah, good idea. I didn't know that was a thing.

**Comment by retep998** [comment]
The hardest part really is just going to be migrating the table. Someone from Gamepedia will have to dig in and change the column type. That said there is only one actual entry in that column at the moment, so I don't mind if they lose the existing data in that column.

**Comment by Alexia** [comment]
You can actually use a "modifyTable" update statement.  I will make a pull request later.

**Comment by Alexia** [comment]
Example from another extension:

$updater->addExtensionUpdate(['modifyField', 'table_name', 'field_name, "{$extDir}/upgrade/sql/wiki_allowed_extensions/change_legacy_load.sql", true]);
