### ISSUE TITLE
Silly return values

### ISSUE THREAD

**Issue by Chocohead** [HydraWiki/Tilesheets#30]
If you ask for the description of a tile without any translation it will return the tilename, instead of what you'd expect of an empty string.

Like {{#itemloc:Macerator|IC2|description|en}} should be "" as there's no translation but it instead returns Macerator, which you'd only expect to occur if you called for the name.

**Comment by elifoster** [comment]
Almost. It returns an empty string when you pass the description AND that item has been localized. It returns the item name regardless of type if the query returns an empty set. That is dumb on my part.
