### ISSUE TITLE
Have list=tiles return the id as one of the fields rather than the key

### ISSUE THREAD

**Issue by retep998** [HydraWiki/Tilesheets#35]
If you look at any other action=query list, you'll notice they all return a simply array without keys. This difference makes writing code that can abstract across all types of action=query really difficult.

**Comment by retep998** [comment]
Also make sure that the id field is actually returned as an integer and not a string, especially since the column in the database is an integer.

**Comment by elifoster** [comment]
You can't have integer keys, so that's why they are strings at the moment.
