### ISSUE TITLE
Getting permission denied when trying to delete tiles

### ISSUE THREAD

**Issue by retep998** [HydraWiki/Tilesheets#36]
When I attempt to delete tiles using my bot account via the API I get the following error.
```json
{
  "error": {
    "*": "See http://ftb.gamepedia.com/api.php for API usage",
    "code": "tspermissiondenied",
    "info": "You do not have permission to delete tiles"
  }
}
```
I'm pretty sure I am logged in to my bot account and my bot account is definitely has the `edittilesheets` right, so I'm not sure what is going on.

**Comment by elifoster** [comment]
I'm not getting this on my local wiki nor the FTB wiki with SatanicBot. Are you sure you're logged in?

**Comment by retep998** [comment]
Resolved that this was an issue with the cookie library I was using mangling my cookies. Everything is working now.
