### ISSUE TITLE
Tile localization and better tooltips

### ISSUE THREAD

**Issue by retep998** [HydraWiki/Tilesheets#8]
In an effort to improve the tilesheet extension the following plan has been laid out which will allow for translation of tilesheet icons as well as improved tooltips. Even translation into English will be useful as it will allow multiple icons on a tilesheet to share the same display name, as well as allowing custom tooltips to be assigned across the wiki.

* [x] Add a table to the database with 4 columns for entry id (matching the entry id in the existing table), language code (such as `en`, `de`, or `ru`), display name, and description.
* [x] Add a special page where translators can translate tilesheet icons, assigning them a display name and description that suits their language.
* [x] For invoking the tilesheet extension add tooltip parameters and having the extension output the appropriate tooltip code, instead of the wrapping template handle it. Order of priority for the tooltip is tooltip parameter at invocation, display name + description from the new table, and defaulting to the item name in the tilesheet itself.

**Comment by elifoster** [comment]
I don't quite understand that last part. Could you clarify the priority thing a bit better?

**Comment by xbony2** [comment]
@elifoster you should work on this, it's a pretty big flaw in the translation system as of now.

Translators shouldn't really have to translate much; in theory translations will be auto-generated based on a comparison between the tilesheet dump file, en_US.lang and other language files. I made a [map](https://gist.github.com/xbony2/816dc2ae3c122c357d8c) for this function a while ago.

**Comment by elifoster** [comment]
Yeah, I probably should. I still need to get my local wiki working properly with all the templates and stuff.

**Comment by retep998** [comment]
@xbony2 To do that automatically all you'd need is an API and then write a program to interact with that API.

**Comment by xbony2** [comment]
Exactly.

**Comment by elifoster** [comment]
So should the table start out like:
```
entry_id  |  display_name  |  description
-----------------------------------------
0         |   Item Name    |  Description
```

Then, you can go and add a language to its known langs, for example:
```
entry_id  |  display_name  |  description  |  display_name_es  |  description_es
```

At which point you can translate the display_name and description into es.

This is how I have started it.

**Comment by retep998** [comment]
No, we are not adding columns for each language.
It should instead be:

entry_id | lang | display_name        | description
---------|------|---------------------|------------
0        | en   | Item name           | Description
0        | es   | Nombre del árticulo | Descripción
